### ISSUE TITLE
Option::<bool>::from_value_opt behavior

### ISSUE THREAD

**Issue by wqfish** [blackbeam/mysql_async#148]
The following code prints `Some(true)`.

```
let value = Value::Int(1);
let out = Option::<bool>::from_value_opt(value).unwrap();
println!("{:?}", out);
```

The following code panics:
```
let value = Value::UInt(1);
let out = Option::<bool>::from_value_opt(value).unwrap();
println!("{:?}", out)
```

Is it expected that `Int(1)` can be converted to `Option<bool>` while `UInt(1)` can't?

BTW I'm on version 0.25. The newer versions fail to compile (a bunch of tokio errors):

```
    Updating crates.io index
   Compiling mysql_async v0.26.0
error[E0425]: cannot find function `spawn` in crate `tokio`
  --> /Users/wqfish/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.26.0/src/conn/pool/ttl_check_inerval.rs:59:24
   |
59 |                 tokio::spawn(idling_conn.conn.disconnect().then(move |_| {
   |                        ^^^^^ not found in `tokio`
   |
help: consider importing one of these items
   |
9  | use crate::conn::pool::mpsc::list::thread::spawn;
   |
9  | use std::thread::spawn;
   |
```

**Comment by blackbeam** [comment]
Hi, @wqfish.

> Is it expected that `Int(1)` can be converted to `Option<bool>` while `UInt(1)` can't?

This behavior is explicitly stated in the docs (see the table [here][1]). Did you get this value from the server or it was created artificially?

Note that you should never get boolean value from the server as `Value::UInt(1)`, even if it's declared as `TINYINT(1) UNSIGNED`.

> BTW I'm on version 0.25. The newer versions fail to compile (a bunch of tokio errors)

Oh, thanks for pointing this out! CI couldn't catch this because of a bug in cargo (see rust-lang/cargo#1796). Please use [`v0.26.1`][2] or [`v0.27.1`][3].

[1]: https://docs.rs/mysql_common/0.26.0/mysql_common 
[2]: https://github.com/blackbeam/mysql_async/releases/tag/v0.26.1
[3]: https://github.com/blackbeam/mysql_async/releases/tag/v0.27.1

**Comment by wqfish** [comment]
Ah just artificial values. I'll look into the docs.
