### ISSUE TITLE
Can we get auto increment generated key values in batch processing

### ISSUE THREAD

**Issue by BharathIO** [blackbeam/mysql_async#156]
In java, we can use the below code to get generated values that work for multiple rows.

```java
ResultSet rs = preparedStatement.getGeneratedKeys();
```
https://docs.oracle.com/javadb/10.8.3.0/ref/crefjavstateautogen.html

In rust, I found `con.last_insert_id()` which is returning only one generated id. Please suggest how to post multiple rows and retrieve all the generated keys at once.

**Comment by blackbeam** [comment]
Hi.

For a single insert statement with multiple rows (`INSERT INTO ... VALUES (...), (...), ...`) I suggest you to use the technique described [here](https://stackoverflow.com/questions/7333524/how-can-i-insert-many-rows-into-a-mysql-table-and-return-the-new-ids). I believe any other approach will actually use this.

Note that this option won't work for multiple insets within `Queryable::batch_exec`. You should use a single insert statement instead, because this is more efficient. Or you could come up with your own version of `batch_exec` that collects the IDs.

**Comment by blackbeam** [comment]
Closing for now. Feel free to reopen.
