### ISSUE TITLE
Implement Queryable for &mut Conn

### ISSUE THREAD

**Issue by roy-ganz** [blackbeam/mysql_async#165]
Hi blackbeam,
sorry for bothering you again.

I'm playing around with Rocket 0.5-rc.1 and the upcoming [db crate](https://github.com/SergioBenitez/Rocket/tree/master/contrib/db_pools) for async databases. MySql is officially supported through sqlx. However you provide a pool yourself, so I try to use your Pool and keep sqlx out. I compiles on my machine. However I have some friction:
- Rockets [Connection](https://github.com/SergioBenitez/Rocket/blob/master/contrib/db_pools/lib/src/database.rs) struct only allows deref /deref_mut to the inner connection.
- Queryable is only implemented for Conn. Looking at the methods, it should be possible to implement it for &mut Conn too.

What do you think about that?

**Comment by blackbeam** [comment]
Hi. May this be a good fit for the [Query](https://docs.rs/mysql_async/0.28.0/mysql_async/prelude/trait.Query.html) trait?
Adapted db_pool's example should look like this (`with` method is provided by the [WithParams](https://docs.rs/mysql_async/0.28.0/mysql_async/prelude/trait.WithParams.html) trait):

```
use mysql_async::prelude::*;

#[get("/<id>")]
async fn read(mut db: Connection<Logs>, id: i64) -> Result<Log> {
    "SELECT content FROM logs WHERE id = ?"
        .with((id,))
        .first(&mut *db)
        .map_ok(|r| Log(r.content))
        .await
}
```

**Comment by roy-ganz** [comment]
Thanks for your quick response.
That would work for queries. However I also need to insert, update and delete, which will require the exec_* functions.
Currently I test my ORM (12 crates, 17K LOC) with a patched rocket_db_pools that allows me to unwrap a Connection<T> into T. 
However I plan to release a beta on crates.io for wider public after my testing is done and therefore I am looking for a more suitable approach.
I will also ask on the rocket side, but would you accept a pull request for Queryable on &mut Conn?

**Comment by blackbeam** [comment]
`impl Queryable for Conn` should cover `&mut Conn` case. Could you please give me a code sample?

**Comment by roy-ganz** [comment]
I have made an example [here](https://github.com/SergioBenitez/Rocket/issues/1790?_pjax=%23repo-content-pjax-container).

**Comment by blackbeam** [comment]
I don't think that it's a good idea in general to have both `Queryable for Conn` and `Queryable for &mut Conn`. `Queryable for Conn` should be enough for both cases.

The problem, as far as I can see, is that you are requiring `x: T` where `T: Queryable` to be the first argument of the `MySqlAsync::from` function but this requirement is impossible to satisfy because `rocket` won't give you `T: Queryable`. 
Since `rocket` is your target have you tried to alter your requirements to match its interface? I mean have you tried to accepting `x: T` where `T: DerefMut<Target=U>, U: Queryable`?
