### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by januwA** [blackbeam/mysql_async#184]
Hello, this library is great, I am learning to use mysql_async, where can I find more examples, thanks.

**Comment by blackbeam** [comment]
Hi. Not sure there are many.

You should note that this library positions itself as a pure rust version of libmysqlclient, so the API surface is quite small.

Regarding examples – please look at the [synchronous clients docs](https://github.com/blackbeam/rust-mysql-simple/). Despite it being synchronous, the code is roughly applicable to the async client, because APIs are quite similar (just add `async` and `await` where needed).
