### ISSUE TITLE
Pool::new does not throw any error if connection url not correct

### ISSUE THREAD

**Issue by surajpayu** [blackbeam/mysql_async#38]
I am working with version 14.1 and gave a incorrect database url. return type should have been Result<Pool> instead of Pool.

**Comment by blackbeam** [comment]
Hi!

Connection url may be incorrect in two different ways:
1. It's ill-formed as an URL (in terms of RFC 3986, i think). This case is asserted by `Pool::new` [here][into_impl] because of [this call][into_call], so call to `Pool::new` will panic.
2. It's correct as an URL but invalid for the database you trying to connect to (i.e. bad user/password, or wrong address). To check this you'll need to create a connection with the database. At the moment `Pool` will not connect to the database until `Pool::get_conn` is called, so `Pool::new` can't verify if your URL is valid or not.

`Pool::new` can't return `Result` because `Conn::new` is asynchronous, but it can return `Future`, and this behavior will match up with the behavior of the synchronous pool (i meant the `Pool` of `mysql` crate). I'll add this in the next version.

[into_impl]: https://docs.rs/mysql_async/0.14.1/src/mysql_async/opts.rs.html#556
[into_call]: https://docs.rs/mysql_async/0.14.1/src/mysql_async/conn/pool/mod.rs.html#69

**Comment by blackbeam** [comment]
Sorry, but i think it's quite inconvenient for `Pool` to have an asynchronous constructor. This will force any containing structure to also have an asynchronous constructor.
