### ISSUE TITLE
Rolling back a transaction during error

### ISSUE THREAD

**Issue by kadfak** [blackbeam/mysql_async#42]
Hi, I'm wondering how to rollback when an error happens mid-transaction. I couldn't find a way to rollback already executed statements because the connection handle cannot be accessed when a future errors.

Here's an example:
```rust
db
    .start_transaction(Default::default())
    .map_err(|_| String::new("transaction error")
    .and_then(|tx|
        // First insertion. This succeeds.
        tx.drop_exec("INSERT ...", ())
            .map_err(|_| String::new("insert1 error"))
    )
    .and_then(|tx|
        // Second insertion. This fails.
        tx.drop_exec("INSERT ...", ())
            .map_err(|_| String::new("insert2 error")) // Couldn't rollback prior insertion
    )
```

In this case, the first insertion succeeds and the second one fails. There is now way to rollback the first insertion.

Furthermore, I couldn't find much information about what happens to the connection after such situation happens. When that same connection is used to carry out another operation, will there be a conflict because the connection has an open transaction which has not been finished?

Am I missing something?

**Comment by blackbeam** [comment]
Hi.

In case of pooled conn, it'll be rolled back because of [this flag][1], that checked [here][2].
In case of plain conn you'll lose the connection and transaction should be rolled back by MySql (but with [some complexities][3] on the way).

> Furthermore, I couldn't find much information about what happens to the connection after such situation happens.

It goes through the [`Drop` impl][4].

I see two kinds of errors from this perspective: one that leads to a broken connection (io error, protocol error and so on), and other that does not (almost every mysql error). At the moment there is no distinction between them and `impl Drop for Conn` is the unified way to recover from both, that highly relies on `Pool`.

[1]: https://github.com/blackbeam/mysql_async/blob/master/src/conn/mod.rs#L53
[2]: https://github.com/blackbeam/mysql_async/blob/de2db1a4cdb0ce46d6f69a8b23476172b7420c72/src/conn/pool/mod.rs#L197
[3]: https://stackoverflow.com/questions/9936699/mysql-rollback-on-transaction-with-lost-disconnected-connection
[4]: https://github.com/blackbeam/mysql_async/blob/de2db1a4cdb0ce46d6f69a8b23476172b7420c72/src/conn/pool/mod.rs#L373

**Comment by kadfak** [comment]
Thanks for an excellent explanation! The `Drop` impl is the key piece that was missing.

I think an example (plus some comments) of how transactions work would be a great addition to the project.
