### ISSUE TITLE
stack overflow with query_result/futures/map

### ISSUE THREAD

**Issue by boxofrox** [blackbeam/mysql_async#8]
Once I corrected the add overflow in #6, I subsequently ran into a stack overflow with the same code unless I limited my query to 341 rows.

```sql
select field1, field2 from table1 limit 342; # doesn't work
select field1, field2 from table1 limit 341; # works
```

The [backtrace](https://gist.github.com/boxofrox/5c521247c840b202050fbc25cde7e4c4) from #6 indicates the problem lies with `src/conn/futures/query_result/futures/map.rs` where it calls `self.poll()`.  I've patched this code in my fork to use `loop {}` instead of recursion, and this has resolved the stack overflow.

Perhaps I made a mistake in my code, but it's derived from the example in the documentation, if so I can submit a PR to improve the docs instead.

Othewise, before I submit the patch I have, shall I convert all the `self.poll()` calls to use `loop {}`?

**Comment by blackbeam** [comment]
Hi!

I'm rewriting huge part of implementation because of inconveniences revealed in real life usage and i hope to finish in one week. Fortunately at this very moment I'm starting to rewrite `map` for `QueryResult` and it would be great to have your patched code for a reference so could you please file a PR?

> Othewise, before I submit the patch I have, shall I convert all the self.poll() calls to use loop {}?

I think this issue applies at least for every `QueryResult` futures (`Collect`, `CollectAll`, `ForEach`, `Map`, `Reduce`, `DropResult`) so it would be great to have them patched.

I will publish a new micro version with your fixes before i finish with rewrite.

Thanks!

**Comment by boxofrox** [comment]
The conversion to use `loop` is fairly trivial.  Not sure if it'll work for all examples.  I'll update the PR for those futures you've mentioned.
